#reading data
s1 <- read.csv("~/Desktop/strava/strava_data_1",sep = ",",header = F)
s2 <- read.csv("~/Desktop/strava/strava_data_2",sep = ",",header = F)
s3 <- read.csv("~/Desktop/strava/strava_data_3",sep = ",",header = F)
s4 <- read.csv("~/Desktop/strava/strava_data_4",sep = ",",header = F)
s5 <- read.csv("~/Desktop/strava/strava_data_5",sep = ",",header = F)
s6 <- read.csv("~/Desktop/strava/strava_data_6",sep = ",",header = F)
s7 <- read.csv("~/Desktop/strava/strava_data_7",sep = ",",header = F)
a <- rbind(s1,s2,s3,s4,s5,s6,s7)

#changing the form of time data
a2 <- as.character(a[,3])
a2 <- strsplit(a2,split=":")
l <- nrow(a)
for(i in 1:l){if(length(a2[[i]])==2){a2[[i]][3]=a2[[i]][2];a2[[i]][2]=a2[[i]][1];a2[[i]][1]="0"}}
b = matrix(1:62688,c(l,3))
for(i in 1:l){b[i,]=a2[[i]]}
time <- rep(0,l)
for(i in 1:l){time[i]=as.numeric(b[i,1])*60+as.numeric(b[i,2])+as.numeric(b[i,2])/60}
a[,3]=time

######### data analysis #########
#### 1.overall data
library(hexbin)
rf<-colorRampPalette(colors = c("#eff3ff","#c6dbef","#9ecae1","#6baed6","#4292c6","#08519c","#08306b"))

a_new <- a[which(a$V2>=4 & a$V2<=11 & a$V3>=20 & a$V3<=80),]
# plot the distribution of raw data
hexbinplot(a_new$V3~a_new$V2,data=a_new,colramp=rf,xbins=70,main = "All Data",xlab = "distance /km", ylab = "time /min")

a_sta <- a
a_sta$V2 <- round(a$V2 - trunc(round(a$V2,1)),1)
a_sta$V3 <- round(a$V3 - trunc(round(a$V3,1)),1)
# plot the histogram of distance fractional data
barplot(table(a_sta$V2),main= "All Data",xlab = "distance fractional part", ylab = "number")
# plot the histogram of time fractional data
barplot(table(a_sta$V3),main= "All Data",xlab = "time fractional part", ylab = "number")




#### 2.data for riding 
a_ride  <- a[which(a[,4]=="Ride"),]
a_ride_new <- a_ride[which(a_ride$V3>=1 & a_ride$V3<=200 & a_ride$V2>=1 & a_ride$V2<=80),] 
# plot the distribution of riding data
hexbinplot(a_ride_new$V3~a_ride_new$V2,data=a_ride_new,colramp=rf,xbins=150,main = "Riding Data",xlab = "distance /km", ylab = "time /min")
# use OLS for regression and get average speed 
plot(V2~V3,data=a_ride_new,pch=16,col='red')
model=lm(V2~V3+0,data=a_ride_new)
abline(model,lty=2)
summary(model)

a_ride_sta <- a_ride_new
a_ride_sta$V2 <- round(a_ride_new$V2 - trunc(round(a_ride_new$V2,1)),1)
a_ride_sta$V3 <- round(a_ride_new$V3 - trunc(round(a_ride_new$V3,1)),1)
# plot the histogram of distance fractional data
barplot(table(a_ride_sta$V2),main= "Riding Data ",xlab = "distance fractional part", ylab = "number")
# plot the histogram of time fractional data
barplot(table(a_ride_sta$V3),main= "Riding Data ",xlab = "time fractional part", ylab = "number")


##### plot 6 graphs in one plot 
par(mfrow = c(3,2))
a_ride_new <- a_ride[which(a_ride$V3>=10 & a_ride$V3<=200 & a_ride$V2>=1 & a_ride$V2<=100),] 
a_ride_sta <- a_ride_new
a_ride_sta$V2 <- round(a_ride_new$V2 - trunc(round(a_ride_new$V2,1)),1)
a_ride_sta$V3 <- round(a_ride_new$V3 - trunc(round(a_ride_new$V3,1)),1)
# plot the histogram of distance fractional data
barplot(table(a_ride_sta$V2),main= "Riding Data (All)",xlab = "distance fractional part", ylab = "number")
# plot the histogram of time fractional data
barplot(table(a_ride_sta$V3),main= "Riding Data (All)",xlab = "time fractional part", ylab = "number")
#range 20~80
a_ride_new <- a_ride[which(a_ride$V3>=20 & a_ride$V3<=80 & a_ride$V2>=3 ),] 
a_ride_sta <- a_ride_new
a_ride_sta$V2 <- round(a_ride_new$V2 - trunc(round(a_ride_new$V2,1)),1)
a_ride_sta$V3 <- round(a_ride_new$V3 - trunc(round(a_ride_new$V3,1)),1)
# plot the histogram of distance fractional data
barplot(table(a_ride_sta$V2),main= "Riding Data (time range: 20min ~ 70min)",xlab = "distance fractional part", ylab = "number")
# plot the histogram of time fractional data
barplot(table(a_ride_sta$V3),main= "Riding Data (time range: 20min ~ 70min)",xlab = "time fractional part", ylab = "number")
#range 80~200
a_ride_new <- a_ride[which(a_ride$V3>=80 & a_ride$V3<=200 & a_ride$V2>=10 ),] 
a_ride_sta <- a_ride_new
a_ride_sta$V2 <- round(a_ride_new$V2 - trunc(round(a_ride_new$V2,1)),1)
a_ride_sta$V3 <- round(a_ride_new$V3 - trunc(round(a_ride_new$V3,1)),1)
# plot the histogram of distance fractional data
barplot(table(a_ride_sta$V2),main= "Riding Data (time range: 70min ~ 200min)",xlab = "distance fractional part", ylab = "number")
# plot the histogram of time fractional data
barplot(table(a_ride_sta$V3),main= "Riding Data (time range: 70min ~ 200min)",xlab = "time fractional part", ylab = "number")
par(mfrow = c(1,1))




#### 3.data for running 
a_run  <- a[which(a[,4]=="Run"),]
a_run_new <- a_run[which(a_run$V2>=1.5 & a_run$V2<=20 & a_run$V3>=5 & a_run$V3<=150),]
# plot the distribution of running data
hexbinplot(a_run_new$V3~a_run_new$V2,data=a_run_new,colramp=rf,xbins=100,main = "Running Data",xlab = "distance /km", ylab = "time /min")
# use OLS for regression and get average speed 
plot(V2~V3,data=a_run_new,pch=16,col='red')
model=lm(V2~V3+0,data=a_run_new)
abline(model,lty=2)
summary(model)

a_run_sta <- a_run_new
a_run_sta$V2 <- round(a_run_new$V2 - trunc(round(a_run_new$V2,1)),1)
a_run_sta$V3 <- round(a_run_new$V3 - trunc(round(a_run_new$V3,1)),1)
# plot the histogram of distance fractional data
barplot(table(a_run_sta$V2),main= "Running Data ",xlab = "distance fractional part", ylab = "number")
# plot the histogram of time fractional data
barplot(table(a_run_sta$V3),main= "Running Data ",xlab = "time fractional part", ylab = "number")
